[project]
name = "todo-py-cli"
version = "0.1.3"
description = "A search utility for TODO statements in codebases."
readme = "README.md"
requires-python = ">=3.10"
dependencies = []
license = "MIT"
license-files = ["LICEN[CS]E*"]
authors = [{ name = "Simon Danielsson", email = "contact@simondanielsson.se" }]

[project.urls]
Homepage = "https://github.com/simon-danielsson/todo.py"

[project.scripts]
todo = "todo.cli:main"
